---
driver:
  name: ec2
  aws_ssh_key_id:  pbradford_aws
  region: us-west-2
  availability_zone: a
  security_group_ids: ["sg-0743bbb8cae7dd2e5"]
  subnet_id: subnet-7424b611
  # image_id: ami-8db945ed
  instance_type: t2.small
  tags:
     created-by : "pbradford"
     Name : "pbtestserver-jenkins"
     OwnerEmail : "pbradford@chef.io"

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[jenkinswrapper::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
